// Successful-workflow plan for every command of src/mcp/commands.json.
//
// Entry/precondition coverage lives in catalog.spec.js. This plan tracks the
// deeper level: one end-to-end success path per command, driven through the
// real front (command bar, pointer, panels, file choosers) and asserting the
// resulting document, then undo/redo where the command edits history.
//
// COVERED names the existing test proving the command. TODO lists the
// scenario still to write; workflow-plan.spec.js registers each entry as
// `test.fixme`, so the Playwright report shows the remaining work. When a
// workflow lands, move its command from TODO to COVERED.

export const COVERED = {
    line: 'workflows.spec.js › LINE creates geometry with undo and redo',
    rectangle: 'workflows.spec.js › RECTANGLE creates geometry with undo and redo',
    circle: 'workflows.spec.js › CIRCLE creates geometry with undo and redo',
    ellipse: 'workflows.spec.js › ELLIPSE creates geometry with undo and redo',
    arc: 'workflows.spec.js › ARC creates geometry with undo and redo',
    point: 'workflows.spec.js › POINT creates geometry with undo and redo',
    xline: 'workflows.spec.js › XLINE creates geometry with undo and redo',
    ray: 'workflows.spec.js › RAY creates geometry with undo and redo',
    polygon: 'workflows.spec.js › POLYGON creates geometry with undo and redo',
    ortho: 'workflows.spec.js › ORTHO changes drafting settings and undo restores them',
    objectTracking: 'workflows.spec.js › OTRACK changes drafting settings and undo restores them',
    dynamicInput: 'workflows.spec.js › DYNMODE changes drafting settings and undo restores them',
    quickSelect: 'workflows.spec.js › line exact coordinates, selection, delete and undo through keyboard',
    delete: 'workflows.spec.js › line exact coordinates, selection, delete and undo through keyboard',
    undo: 'workflows.spec.js › line exact coordinates, selection, delete and undo through keyboard',
    redo: 'workflows.spec.js › LINE creates geometry with undo and redo',
    divide: 'workflows.spec.js › DIVIDE places points at exact distances and restores in one undo',
    measure: 'workflows.spec.js › MEASURE places points at exact distances and restores in one undo',
    move: 'workflows.spec.js › MOVE transforms a selected line and undo preserves its identity',
    copy: 'workflows.spec.js › COPY transforms a selected line and undo preserves its identity',
    scale: 'workflows.spec.js › SCALE transforms a selected line and undo preserves its identity',
    rotate: 'workflows.spec.js › ROTATE transforms a selected line and undo preserves its identity',
    widePolyline: 'workflows.spec.js › PLINE 0.2 0.2 completes a compound creation',
    multiline: 'workflows.spec.js › MLINE completes a compound creation',
    spline: 'workflows.spec.js › SPLINE completes a compound creation',
    donut: 'workflows.spec.js › DONUT 2 4 completes a compound creation',
    revisionCloud: 'workflows.spec.js › REVCLOUD RECT 0.5 completes a compound creation',
    table: 'workflows.spec.js › TABLE 2 3 completes a compound creation',
    hatch: 'workflows.spec.js › HATCH fills a closed boundary and undo retains the source',
    solid: 'workflows.spec.js › SOLID fills a closed boundary and undo retains the source',
    gradient: 'workflows.spec.js › GRADIENT fills a closed boundary and undo retains the source',
    blockDefine: 'workflows.spec.js › BLOCK, INSERT and EXPLODE retain native source geometry',
    blockInsert: 'workflows.spec.js › BLOCK, INSERT and EXPLODE retain native source geometry',
    explode: 'workflows.spec.js › BLOCK, INSERT and EXPLODE retain native source geometry',
    group: 'workflows.spec.js › GROUP, UNGROUP, HIDEOBJECTS and UNISOLATEOBJECTS preserve geometry',
    ungroup: 'workflows.spec.js › GROUP, UNGROUP, HIDEOBJECTS and UNISOLATEOBJECTS preserve geometry',
    hideObjects: 'workflows.spec.js › GROUP, UNGROUP, HIDEOBJECTS and UNISOLATEOBJECTS preserve geometry',
    unisolateObjects: 'workflows.spec.js › GROUP, UNGROUP, HIDEOBJECTS and UNISOLATEOBJECTS preserve geometry',
    saveAs: 'workflows.spec.js › drawing archive downloads and reopens through the actual file input',
    new: 'workflows.spec.js › drawing archive downloads and reopens through the actual file input',
    open: 'workflows.spec.js › drawing archive downloads and reopens through the actual file input',
    viewport: 'workflows.spec.js › publication writes a real downloadable PDF from the front',
    pdf: 'workflows.spec.js › publication writes a real downloadable PDF from the front',
    dxfImport: 'cad.spec.js › DXFIN uses the file picker, converts millimetres and undoes the whole import',
    dxfExport: 'cad.spec.js › DXFOUT produces a real metre-based file without changing history',
    // DWG needs the desktop runtime and LibreDWG: covered natively, not in the browser.
    dwgImport: 'npm run test:headless › native DWG export → import → undo through MCP (LUMCAD_LIBREDWG_DIR)',
    dwgExport: 'npm run test:headless › native DWG export → import → undo through MCP (LUMCAD_LIBREDWG_DIR)',
};

// TODO(e2e): every entry below is a pending successful workflow.
export const TODO = {
    // TODO(e2e): drawing and annotation creation — create through command input
    // and pointer, assert exact geometry/properties, Escape leaves no partial
    // object, undo removes it and redo restores the same IDs.
    creation: {
        text: 'TEXT: pick a frame, type a label in the in-place editor, commit; assert text, position and font size; undo/redo',
        multilineText: 'MTEXT: draw a frame, type two paragraphs with bold in the rich editor; assert wrapping width and runs; undo/redo',
        sketch: 'SKETCH 0.05 POLYLINE: drag a freehand stroke with the pointer; release commits one polyline with sampled vertices; undo',
        breakLine: 'BREAKLINE 0.5: pick two endpoints; assert the zigzag polyline keeps its parameters; edit size via panel; undo',
        leader: 'MLEADER "Roof": pick arrow and landing points; assert leader text, arrowhead and landing; undo/redo',
        tolerance: 'TOLERANCE position 0.1 DIAMETER DATUM A: place the frame; assert rows and datum cells; edit; undo',
        wipeout: 'WIPEOUT on a selected closed polygon over a line: assert mask above the line, line untouched; undo',
        region: 'REGION on a selected closed rectangle: assert one region with the exact outline, sources kept; undo',
        boundary: 'BOUNDARY: pick inside two overlapping rectangles; assert the closed boundary of the picked area; undo',
        centerLine: 'CENTERLINE on two parallel lines: assert the associative centre line moves when a source moves; undo',
        centerMark: 'CENTERMARK on a picked circle: assert mark size/extension, follows circle edits; undo',
        arcText: 'ARCTEXT "Roof" HEIGHT 0.3 on a selected arc: text follows arc edits; EDIT and DETACH; undo/redo',
        field: 'FIELD on a selected text with OBJECT id length: assert field value, then UPDATEFIELD after the line changes',
        pointStyle: 'DDPTYPE cross 0.2 with a selected point: assert default style and the point updated; undo',
        temporaryTrackingPoint: 'TRACKPOINT during LINE: acquire a tracking origin, type an offset, assert the resulting vertex',
    },
    // TODO(e2e): modification — build a known fixture, select it through the
    // front, run the command, assert exact coordinates and preserved IDs,
    // then undo restores the fixture exactly and redo reapplies it.
    modification: {
        offset: 'OFFSET 1 on a line toward a picked side: assert the parallel copy at exactly 1 m; undo',
        trim: 'TRIM: two crossing lines, pick one portion; assert the remaining segment ends at the intersection; undo',
        extend: 'EXTEND: pick a short line end toward a boundary line; assert the new endpoint on the boundary; undo',
        mirror: 'MIRROR with a two-point axis, keep source: assert reflected coordinates and source unchanged; undo',
        array: 'ARRAY rectangular 3×2 on a circle: set spacing, ARRAYCLOSE; assert 6 instances in one array; undo',
        arrayPolar: 'ARRAYPOLAR COUNT 6 around a picked centre: assert angular spacing of instances; undo',
        arrayPath: 'ARRAYPATH along a polyline: COUNT 5; assert instances placed along the path; undo',
        arrayEdit: 'ARRAYEDIT on an existing rectangular array: change rows, ARRAYCLOSE; assert parameters and count; undo',
        arrayClose: 'ARRAYCLOSE during ARRAY preview commits; during ARRAYEDIT it applies the edit (covered with ARRAY/ARRAYEDIT)',
        break: 'BREAK on a line between two picked points: assert two lines with the exact gap; undo',
        breakAtPoint: 'BREAKATPOINT on a line: assert two lines sharing the picked point, IDs stable for the first; undo',
        stretch: 'STRETCH with a crossing window over one end of a rectangle: assert moved vertices only; undo',
        lengthen: 'LENGTHEN DELTA 2 on a picked line end: assert length +2 m from that end; undo',
        join: 'JOIN two endpoint-connected lines: assert one polyline with both parts in order; undo',
        xplode: 'XPLODE on a polyline with explicit layer handling: assert parts and their properties; undo',
        align: 'ALIGN with two point pairs: assert translated/rotated geometry; undo',
        fillet: 'FILLET RADIUS 1 on two perpendicular lines: assert tangent arc of radius 1 and trimmed lines; undo',
        chamfer: 'CHAMFER 1 1 on two perpendicular lines: assert bevel segment and trimmed lines; undo',
        blend: 'BLEND between two open line ends: assert a cubic spline tangent to both; undo',
        polylineEdit: 'PEDIT VERTEX/INSERT on a polyline: assert vertex coordinates, then CLOSE; undo',
        splineEdit: 'SPLINEDIT on a spline: move one control point through the panel; assert curve update; undo',
        multilineEdit: 'MLEDIT SCALE 2 on a multiline and DIAMETERS on a donut: assert updated parameters; undo',
        hatchEdit: 'HATCHEDIT LINES 0.5 45 on a hatch: assert pattern change and boundary association kept; undo',
        hatchToBack: 'HATCHTOBACK: hatch drawn after a line moves behind it in draw order; undo',
        drawOrder: 'DRAWORDER BACK on the last line: assert the entity order; undo',
        textToFront: 'TEXTTOFRONT: text below a solid fill moves to the front, relative order kept; undo',
        transparency: 'TRANSPARENCY 50 on a selection: assert the override; undo',
        flatten: 'FLATTEN PREVIEW then FLATTEN ALL on an imported fixture with residual z: assert z cleared, XY kept; undo',
        overkill: 'OVERKILL on duplicate and overlapping lines: assert duplicates removed and merge result; undo',
        revisionProperties: 'REVCLOUDPROPERTIES 0.8 REVERSE on a revision cloud: assert arc length and direction; undo',
        matchProperties: 'MATCHPROP from a red dashed line to a target: assert colour, line type and layer copied; undo',
        layerMatch: 'LAYMCH: move a target to the source object layer only; undo',
        copyToLayer: 'COPYTOLAYER "Annotations": assert in-place copies on the target layer; undo',
        textEdit: 'TEXTEDIT on a text: change content in the rich editor; assert text; undo',
        creationPanel: 'CREATIONPANEL with a selected circle: edit radius in the Properties tab; assert geometry; undo',
        resetBlock: 'RESETBLOCK on a dynamic block instance with changed parameters: assert defaults restored; undo',
    },
    // TODO(e2e): dimensions and annotation styles — dimension known geometry,
    // assert measured value/label and associativity (moving the source updates
    // the dimension), and style changes through command and panel.
    annotation: {
        dimension: 'DIMENSION on a picked line: assert adaptive linear value 10 and associativity after MOVE',
        linearDimension: 'DIMLINEAR on an inclined line: assert horizontal value; undo',
        alignedDimension: 'DIMALIGNED on an inclined line: assert true length; undo',
        rotatedDimension: 'DIMROTATED 30 on a line: assert projected length; undo',
        angularDimension: 'DIMANGULAR on two lines at 90°: assert 90° label; undo',
        arcDimension: 'DIMARC on an arc: assert arc length; undo',
        radiusDimension: 'DIMRADIUS on a circle r=5: assert R5 label; follows radius edit',
        diameterDimension: 'DIMDIAMETER on a circle r=5: assert Ø10 label',
        joggedDimension: 'DIMJOGGED on a large arc: assert jog placement and value',
        ordinateDimension: 'DIMORDINATE X on a point: assert ordinate value from origin',
        quickDimension: 'QDIM on three collinear lines: assert continuous series values; QDIM BASELINE FIRST',
        baselineDimension: 'DIMBASELINE from a linear dimension: assert baseline series spacing and values',
        continueDimension: 'DIMCONTINUE from a linear dimension: assert chained values',
        dimensionBreak: 'DIMBREAK with two points on a dimension: assert manual gap; undo',
        dimensionSpace: 'DIMSPACE on parallel linear dimensions: assert equal spacing; undo',
        dimensionTextEdit: 'DIMTEDIT: move a dimension label; measured geometry unchanged; undo',
        dimensionEdit: 'DIMEDIT "<> m": assert label override keeps measured value; undo',
        dimensionDisassociate: 'DIMDISASSOCIATE: moving the source no longer updates the dimension; undo',
        dimensionReassociate: 'DIMREASSOCIATE to another line: assert value follows the new source; undo',
        dimensionUpdate: 'DIMUPDATE "Architectural": assert style applied to selected dimensions; undo',
        dimensionRegenerate: 'DIMREGEN after a style edit: assert refreshed appearance with overrides kept',
        dimensionInspect: 'DIMINSPECT ON "Check" "100%": assert inspection frame; OFF removes it',
        dimensionStyle: 'DIMSTYLE: create, rename and set current through the panel; assert new dimensions use it',
        centerReassociate: 'CENTERREASSOCIATE a centre mark to another circle: assert it follows the new circle',
        centerDisassociate: 'CENTERDISASSOCIATE: moving the circle no longer moves the mark; undo',
        centerReset: 'CENTERRESET on a resized centre mark: assert default size/extension; undo',
        multiLeaderEdit: 'MLEADEREDIT TEXT "New" and ADD a branch: assert content and branches; undo',
        multiLeaderAlign: 'MLEADERALIGN X on two leaders: assert aligned content origins; undo',
        multiLeaderCollect: 'MLEADERCOLLECT on three leaders: assert one leader with all branches; undo',
        multiLeaderStyle: 'MLEADERSTYLE SAVE then USE: assert new leaders take text/arrow sizes',
        textStyle: 'STYLE: create a text style in the manager, apply it to a text; assert font/height; undo',
        multilineStyle: 'MLSTYLE SET "Wall" with two elements, then MLINE STYLE "Wall": assert offsets',
        tableStyle: 'TABLESTYLE SET "Grid" then APPLY to a table: assert padding/row height; undo',
        tableEdit: 'TABLEDIT: edit a cell value and a formula, merge two cells; assert results; undo',
        tableExport: 'TABLEEXPORT VALUES: download CSV from a 2×3 table; assert file rows',
        dataLink: 'DATALINK ATTACH via picker with a CSV: assert table cells and source metadata; DETACH',
        dataLinkUpdate: 'DATALINKUPDATE after replacing the CSV: assert refreshed cells in one undo step',
        updateField: 'UPDATEFIELD ALL after geometry changes: assert field texts refreshed in one undo step',
        objectScale: 'OBJECTSCALE ADD 50 on annotative text: assert representation per scale; undo',
        scaleListEdit: 'SCALELISTEDIT ADD 75 and CURRENT 75: assert catalogue and current scale',
        annotationUpdate: 'ANNOUPDATE on annotative objects after a scale change: assert rebased representation',
        annotationReset: 'ANNORESET: assert per-scale offsets cleared, scale list kept; undo',
        hyperlink: 'HYPERLINK SET "https://example.org" "Spec" on a line: assert link metadata; REMOVE; undo',
    },
    // TODO(e2e): constraints and parameters — build lines/circles, apply the
    // relation, assert solved geometry, then edit a parameter and check the
    // dependent geometry; undo restores the unconstrained state.
    constraints: {
        geomConstraint: 'GEOMCONSTRAINT horizontal 1, LIST, DELETE: assert relation lifecycle',
        gcCoincident: 'GCCOINCIDENT 1@end 2@start: assert the endpoints meet',
        gcCollinear: 'GCCOLLINEAR on two lines: assert the second line on the first line axis',
        gcConcentric: 'GCCONCENTRIC on two circles: assert identical centres',
        gcEqual: 'GCEQUAL on two lines: assert equal lengths',
        gcFix: 'GCFIX on a point then move a constrained line: assert the fixed point stays',
        gcHorizontal: 'GCHORIZONTAL on an inclined line: assert equal Y at both ends',
        gcParallel: 'GCPARALLEL on two lines: assert parallel directions',
        gcPerpendicular: 'GCPERPENDICULAR on two lines: assert 90° between them',
        gcSymmetric: 'GCSYMMETRIC on two points and an axis line: assert mirrored positions',
        gcTangent: 'GCTANGENT on a line and a circle: assert distance centre-line equals radius',
        gcVertical: 'GCVERTICAL on an inclined line: assert equal X at both ends',
        gcSmooth: 'GCSMOOTH between a spline and a line: assert G2 continuity at the joint',
        autoConstrain: 'AUTOCONSTRAIN PREVIEW then apply on a near-rectangle: assert detected relations, one undo',
        dimConstraint: 'DIMCONSTRAINT linear width "4" X 1: assert line length 4; SET width "6"',
        dcLinear: 'DCLINEAR w "4" X: assert horizontal driving distance',
        dcAligned: 'DCALIGNED d "5": assert aligned length 5',
        dcAngular: 'DCANGULAR a "30": assert angle between two lines',
        dcRadius: 'DCRADIUS r "2": assert circle radius 2',
        dcDiameter: 'DCDIAMETER d "6": assert circle diameter 6',
        dcConvert: 'DCCONVERT on an associative linear dimension: assert named driving constraint',
        parameters: 'PARAMETERS SET width distance "3" then a formula referencing it: assert solved geometry',
    },
    // TODO(e2e): blocks and attributes — define blocks through the front,
    // edit them in BEDIT, assert every reference updates and attribute values
    // are kept; undo/redo across the model history.
    blocks: {
        blockEdit: 'BEDIT "Test block": add a line in the draft; assert draft isolation from the model',
        blockSave: 'BSAVE in BEDIT: assert every reference shows the new line in one undo step',
        blockClose: 'BCLOSE DISCARD: assert the definition unchanged; BCLOSE SAVE applies',
        blockSearch: 'BSEARCH "roof": assert the Library tab filters definitions',
        contentBrowser: 'ADCENTER OPEN via picker on a library .lcad: insert a listed block',
        blockExport: 'WBLOCK LIBRARY: download a block library .lcad and reopen it with BLOCKIMPORT',
        blockImport: 'BLOCKIMPORT via picker: assert imported definitions with collision-safe names',
        blockBase: 'BASE 2 3: assert the insertion base point; undo',
        blockDetect: 'BLOCKDETECT on a motif repeated three times: assert three matches reported, no edit',
        blockConvert: 'BCONVERT "Panel": assert motifs replaced by references in one undo step',
        blockReplace: 'BLOCKREPLACE "Other": assert reference IDs/transforms kept, definition swapped; undo',
        blockLookupTable: 'BLOOKUPTABLE SET in BEDIT: assert lookup row; apply with BTABLE',
        blockTable: 'BTABLE APPLY table choice on a dynamic instance: assert outputs; undo',
        blockVisibility: 'BVSTATE SET in BEDIT and switch state on an instance: assert visible members',
        blockParameter: 'BPARAMETER SET width distance 2 in BEDIT, then SET width 3 outside: assert geometry',
        blockAction: 'BACTION STRETCH bound to a parameter: changing the parameter stretches the members',
        blockCount: 'BCOUNT: assert counts including nested references in the measurements panel',
        attributeDefine: 'ATTDEF in BEDIT: define TAG with prompt/default; assert definition in the Library tab',
        attributeEdit: 'ATTEDIT TAG "A12" on a reference: assert value; undo',
        attributeSync: 'ATTSYNC after adding a definition: assert references gain the attribute with defaults',
        attributeDisplay: 'ATTDISP OFF/ALL/NORMAL: assert attribute visibility modes',
        attributeManager: 'BATTMAN: reorder and edit a definition in the panel; assert references updated',
        attributeExtract: 'ATTEXT CSV: download values of nested references; assert rows',
        pasteBlock: 'PASTEBLOCK after COPYCLIP: assert one anonymous block reference at the picked point',
    },
    // TODO(e2e): layers, selection, inquiry and views — assert panel state,
    // selection sets and reported values (Measurements panel / message) on a
    // known fixture; non-persistent inquiries must not add history.
    layersSelectionInquiry: {
        select: 'SELECT then window/crossing selection with the pointer: assert selected IDs',
        groupEdit: 'GROUPEDIT "Roof" ADD/REMOVE/RENAME and OFF: assert membership and collective selection; undo',
        isolateObjects: 'ISOLATEOBJECTS: assert hiddenObjectIds hold every other object; UNISOLATEOBJECTS restores',
        selectionFilter: 'FILTER SAVE "Red" COLOR #ff0000 then APPLY "Red": assert selection',
        selectSimilar: 'SELECTSIMILAR from one line: assert all lines on the same layer selected',
        selectCount: 'SELECTCOUNT: assert rows by type/layer in the Measurements panel',
        countObjects: 'COUNT ALL: assert reported counts',
        countArea: 'COUNTAREA 0 0 10 10: assert objects wholly inside counted',
        countList: 'COUNTLIST GROUP type,layer: assert rows; no history entry',
        countTable: 'COUNTTABLE 0 0 LINKED: assert a query-backed table refreshed after a new object',
        dataExtract: 'DATAEXTRACTION CSV download: assert extracted fields/rows',
        measureGeometry: 'MEASUREGEOM DISTANCE on two points: assert distance and delta; ANGLE and AREA modes',
        distanceInquiry: 'DIST 0 0 3 4: assert distance 5 and no history entry',
        areaInquiry: 'AREA on a selected 10×5 rectangle: assert area 50 and perimeter 30',
        coordinateInquiry: 'ID 2 3: assert reported coordinates in model units',
        entityList: 'LIST on a selected circle: assert centre/radius rows',
        drawingStatus: 'STATUS: assert object/layer/block counts',
        massProperties: 'MASSPROP on a rectangle: assert area, centroid and moments',
        layerState: 'LAYERSTATE SAVE/RESTORE: hide a layer, restore; assert visibility',
        layerStateSave: 'LAYERSTATESAVE "Plan": assert state stored in the catalogue',
        layerIsolate: 'LAYISO on a selected object: assert other layers off; undo',
        layerUnisolate: 'LAYUNISO after LAYISO: assert the captured state restored',
        layerWalk: 'LAYWALK "Walls" then END: assert temporary visibility and restoration',
        layerMerge: 'LAYMRG "A" "B": assert entities remapped and A removed; undo',
        layerTranslate: 'LAYTRANS "A" "B": assert mapping into existing layers; undo',
        layerFilter: 'LAYERFILTER "dim locked": assert the Layers tab list filtered',
        layerFlags: 'LAYER "Walls" LOCK ON: assert locked layer refuses edits; undo',
        layerCurrent: 'LAYMCUR on a picked object: assert current layer',
        namedView: 'VIEW SAVE "Roof" after zooming, then RESTORE: assert viewport',
        viewGo: 'VIEWGO "Roof": assert restored viewport without history entry',
        zoom: 'ZOOM 2: assert viewport width halves around the centre',
        fit: 'EXTENTS: assert the viewport contains all visible objects',
        pan: 'PAN: drag the canvas with the pointer; assert viewport translation without history entry',
        quickCalc: 'QUICKCALC x=2*3 then x+1: assert result 7 and session variable',
    },
    // TODO(e2e): drafting settings and coordinate systems — change the setting
    // through command and status-bar controls, then prove its effect on point
    // input (snapping/limits/UCS) with exact coordinates.
    drafting: {
        polar: 'POLAR 45: draw a line near 45°; assert the snapped angle',
        draftingSettings: 'DSETTINGS: change polar increment in the panel; assert settings and effect',
        drawingUnits: 'UNITS DISPLAY mm PRECISION 1: assert formatted lengths in inquiries',
        ucs: 'UCS SET 10 0 90: typed point 1,0 lands at world 10,1; UCS WORLD restores',
        ucsIcon: 'UCSICON OFF/ON: assert indicator visibility',
        drawingLimits: 'LIMITS 0 0 10 10: point outside is refused; OFF accepts it',
    },
    // TODO(e2e): layouts and publication — create layouts/viewports through the
    // front, check paper-space state, and read every produced file (PDF page
    // count/size, image dimensions, SVG/WMF headers, ZIP contents).
    layoutsPublishing: {
        layout: 'LAYOUT with a standard arrangement: assert new layout and active paper space',
        pageSetup: 'PAGESETUP: change paper size and margins; assert layout page setup; undo',
        pageSetupImport: 'PSETUPIN via picker from a drawing with profiles: assert imported profiles',
        pageSetupExport: 'PSETOUT: download setup drawing; reopen and assert profiles',
        modelSpace: 'MODEL from a layout: assert workspace model',
        paperSpace: 'PSPACE: assert active layout in paper workspace',
        viewportClip: 'VPCLIP with a polygon on a viewport: assert clip boundary; undo',
        viewportLayer: 'VPLAYER: freeze a layer in one viewport; assert per-viewport override',
        viewportMax: 'VPMAX on a viewport: assert maximised model navigation',
        viewportMin: 'VPMIN: assert return to the full layout',
        alignSpace: 'ALIGNSPACE with model and paper point pairs: assert viewport scale/centre',
        changeSpace: 'CHSPACE: move a model object to the layout keeping its displayed placement; undo',
        exportLayout: 'EXPORTLAYOUT: download the layout as a model drawing; reopen and assert geometry',
        plot: 'PLOT: change scale and area in the preview; Save PDF; assert page size',
        pdfAll: 'PDFALL with two mixed-size layouts: assert PDF page count and sizes',
        pdfSelected: 'PDFSELECTED with two selected layout tabs: assert two ordered pages',
        publish: 'PUBLISH: assert multi-layout preview and PDF output',
        autoPublish: 'AUTOPUBLISH (desktop): PDF written beside the saved drawing; browser refusal message',
        dwfx: 'DWFXOUT: download DWFx; assert ZIP package with one page per layout',
        pngOut: 'PNGOUT WIDTH 256: assert PNG dimensions 256 px wide',
        jpegOut: 'JPGOUT WIDTH 256 BACKGROUND #ffffff: assert JPEG header and size',
        svgOut: 'SVGOUT: assert SVG contains the line geometry',
        wmfExport: 'WMFOUT: assert WMF placeable header and records',
        styleManager: 'STYLESMANAGER: create a plot style in the panel; assert catalogue',
        plotStyle: 'PLOTSTYLE SAVE then APPLY to a selection: assert plotted appearance in PDF',
        convertPlotStyles: 'CONVERTPSTYLES NAMED: assert mapping mode and assignments; undo',
        convertColorTable: 'CONVERTCTB: assert colour table converted to named assignments; undo',
        newSheetSet: 'NEWSHEETSET "Project": assert empty sheet set in editor state',
        openSheetSet: 'OPENSHEETSET via picker: assert ordered sheets',
        sheetSet: 'SHEETSET ADD CURRENT layout and REPORT: assert sheet rows; SAVE downloads the index',
        sheetSetArchive: 'ETRANSMIT (desktop): ZIP contains index, drawings and dependencies',
    },
    // TODO(e2e): files, references and imports — exercise the browser file
    // chooser/download (or the desktop-only refusal), assert imported geometry,
    // atomic refusal of invalid inputs and a single undo entry per import.
    filesReferences: {
        saveTemplate: 'SAVETEMPLATE: download a .lcad template; NEW TEMPLATE with it reproduces content',
        quickNew: 'QNEW with a configured template (desktop) and blank fallback in the browser',
        recover: 'RECOVER via picker with a damaged .lcad: REPORT, then OPEN the candidate',
        recoverAll: 'RECOVERALL (desktop): batch report over a root drawing and its references',
        recoveryManager: 'RECOVERYMANAGER SELECT 1 after RECOVERALL: assert candidate details',
        audit: 'AUDIT CHECK on a drawing with an invalid layer reference, then REPAIR; undo',
        purge: 'PURGE PREVIEW then PURGE ALL: assert unused blocks/layers removed; undo',
        drawingCompare: 'COMPARE via picker against an edited copy: assert reported changes',
        drawingCompareImport: 'COMPAREIMPORT 1: assert the selected change imported in one undo step',
        drawingStandards: 'STANDARDS SAVE download, then LOAD via picker: assert embedded standards',
        drawingCheckStandards: 'CHECKSTANDARDS then FIX ALL: assert issues repaired; undo',
        externalReference: 'XREF LIST/RELOAD/UNLOAD/DETACH on an attached reference: assert states',
        referenceAttach: 'XATTACH via picker: assert cached reference geometry at the insertion point',
        referenceBind: 'XBIND: assert reference converted to native block geometry; undo',
        referenceClip: 'XCLIP RECT on a reference: assert clipped rendering bounds; undo',
        referenceCompare: 'XCOMPARE after the source changed: assert added/removed entities',
        referenceEdit: 'REFEDIT (desktop): edit the source draft in place',
        referenceSave: 'REFSAVE (desktop): source file rewritten atomically, host cache reloaded',
        referenceClose: 'REFCLOSE DISCARD and SAVE (desktop): draft lifecycle',
        imageAttach: 'IMAGEATTACH (desktop path) and browser refusal: assert linked image entity',
        imageSource: 'IMAGE RELINK/EMBED on an image: assert source metadata; undo',
        imageClip: 'IMAGECLIP RECT on an image: assert crop; undo',
        imageAdjust: 'IMAGEADJUST BRIGHTNESS 20: assert adjustment; undo',
        pdfImport: 'PDFIMPORT via picker with a vector PDF: assert imported geometry/text in one undo step',
        pdfAttach: 'PDFATTACH via picker: assert underlay page and scale',
        pdfClip: 'PDFCLIP RECT on an underlay: assert clip; undo',
        pdfLayers: 'PDFLAYERS LIST then OFF a layer: assert visibility change',
        pdfShxText: 'PDFSHXTEXT with imported SHX strokes and a font file: assert recognised text',
        dgnImport: 'DGNIMPORT via picker with a V7 fixture: assert levels/geometry in one undo step',
        dgnAttach: 'DGNATTACH via picker: assert vector reference with embedded source',
        dgnClip: 'DGNCLIP RECT on a DGN reference: assert clip; undo',
        dwfAttach: 'DWFATTACH via picker with a DWFx page: assert underlay and preview',
        dwfClip: 'DWFCLIP RECT on a DWFx underlay: assert crop; undo',
        wmfImport: 'WMFIN via picker with a WMF fixture: assert editable vector geometry; undo',
        copyClip: 'COPYCLIP then PASTECLIP: assert pasted copies at the picked point',
        copyBase: 'COPYBASE with a base point then PASTECLIP: assert placement relative to the base',
        cutClip: 'CUTCLIP: assert removal only after the clipboard write; undo',
        pasteClip: 'PASTECLIP of LUMCAD and SVG clipboard content: assert geometry',
        pasteOriginal: 'PASTEORIG: assert pasted copies at original coordinates',
        aliasEdit: 'ALIASEDIT SET MYL line then MYL: assert alias drives LINE; REMOVE',
    },
};
