// Successful-workflow plan for every command of src/mcp/commands.json.
//
// Entry/precondition coverage lives in catalog.spec.js. This plan tracks the
// deeper level: one end-to-end success path per command, driven through the
// real front (command bar, pointer, panels, file choosers) and asserting the
// resulting document, then undo/redo where the command edits history.
//
// COVERED names the existing test proving the command. TODO lists the
// scenario still to write; workflow-plan.spec.js registers each entry as
// `test.fixme`, so the Playwright report shows the remaining work. When a
// workflow lands, move its command from TODO to COVERED.

export const COVERED = {
    line: 'workflows.spec.js › LINE creates geometry with undo and redo',
    rectangle: 'workflows.spec.js › RECTANGLE creates geometry with undo and redo',
    circle: 'workflows.spec.js › CIRCLE creates geometry with undo and redo',
    ellipse: 'workflows.spec.js › ELLIPSE creates geometry with undo and redo',
    arc: 'workflows.spec.js › ARC creates geometry with undo and redo',
    point: 'workflows.spec.js › POINT creates geometry with undo and redo',
    xline: 'workflows.spec.js › XLINE creates geometry with undo and redo',
    ray: 'workflows.spec.js › RAY creates geometry with undo and redo',
    polygon: 'workflows.spec.js › POLYGON creates geometry with undo and redo',
    ortho: 'workflows.spec.js › ORTHO changes drafting settings and undo restores them',
    objectTracking: 'workflows.spec.js › OTRACK changes drafting settings and undo restores them',
    dynamicInput: 'workflows.spec.js › DYNMODE changes drafting settings and undo restores them',
    quickSelect: 'workflows.spec.js › line exact coordinates, selection, delete and undo through keyboard',
    delete: 'workflows.spec.js › line exact coordinates, selection, delete and undo through keyboard',
    undo: 'workflows.spec.js › line exact coordinates, selection, delete and undo through keyboard',
    redo: 'workflows.spec.js › LINE creates geometry with undo and redo',
    divide: 'workflows.spec.js › DIVIDE places points at exact distances and restores in one undo',
    measure: 'workflows.spec.js › MEASURE places points at exact distances and restores in one undo',
    move: 'workflows.spec.js › MOVE transforms a selected line and undo preserves its identity',
    copy: 'workflows.spec.js › COPY transforms a selected line and undo preserves its identity',
    scale: 'workflows.spec.js › SCALE transforms a selected line and undo preserves its identity',
    rotate: 'workflows.spec.js › ROTATE transforms a selected line and undo preserves its identity',
    widePolyline: 'workflows.spec.js › PLINE 0.2 0.2 completes a compound creation and restores exactly through history',
    multiline: 'workflows.spec.js › MLINE completes a compound creation and restores exactly through history',
    spline: 'workflows.spec.js › SPLINE completes a compound creation and restores exactly through history',
    donut: 'workflows.spec.js › DONUT 2 4 completes a compound creation and restores exactly through history',
    revisionCloud: 'workflows.spec.js › REVCLOUD RECT 0.5 completes a compound creation and restores exactly through history',
    table: 'workflows.spec.js › TABLE 2 3 completes a compound creation and restores exactly through history',
    hatch: 'workflows.spec.js › HATCH fills a closed boundary and undo retains the source',
    solid: 'workflows.spec.js › SOLID fills a closed boundary and undo retains the source',
    gradient: 'workflows.spec.js › GRADIENT fills a closed boundary and undo retains the source',
    blockDefine: 'workflows.spec.js › BLOCK, INSERT and EXPLODE retain native source geometry',
    blockInsert: 'workflows.spec.js › BLOCK, INSERT and EXPLODE retain native source geometry',
    explode: 'workflows.spec.js › BLOCK, INSERT and EXPLODE retain native source geometry',
    group: 'workflows.spec.js › GROUP, UNGROUP, HIDEOBJECTS and UNISOLATEOBJECTS preserve geometry',
    ungroup: 'workflows.spec.js › GROUP, UNGROUP, HIDEOBJECTS and UNISOLATEOBJECTS preserve geometry',
    hideObjects: 'workflows.spec.js › GROUP, UNGROUP, HIDEOBJECTS and UNISOLATEOBJECTS preserve geometry',
    unisolateObjects: 'workflows.spec.js › GROUP, UNGROUP, HIDEOBJECTS and UNISOLATEOBJECTS preserve geometry',
    saveAs: 'workflows.spec.js › drawing archive downloads and reopens through the actual file input',
    new: 'workflows.spec.js › drawing archive downloads and reopens through the actual file input',
    open: 'workflows.spec.js › drawing archive downloads and reopens through the actual file input',
    viewport: 'workflows.spec.js › publication writes a real downloadable PDF from the front',
    pdf: 'workflows.spec.js › publication writes a real downloadable PDF from the front',
    dxfImport: 'cad.spec.js › DXFIN uses the file picker, converts millimetres and undoes the whole import',
    dxfExport: 'cad.spec.js › DXFOUT produces a real metre-based file without changing history',
    // DWG needs the desktop runtime and LibreDWG: covered natively, not in the browser.
    dwgImport: 'npm run test:headless › native DWG export → import → undo through MCP (LUMCAD_LIBREDWG_DIR)',
    dwgExport: 'npm run test:headless › native DWG export → import → undo through MCP (LUMCAD_LIBREDWG_DIR)',
    text: 'tools-creation.spec.js › TEXT creates a single-line label typed in the in-place editor',
    multilineText: 'tools-creation.spec.js › MTEXT keeps typed paragraphs on separate lines',
    sketch: 'tools-creation.spec.js › SKETCH records typed samples as one sampled polyline',
    breakLine: 'tools-creation.spec.js › BREAKLINE creates an editable zigzag between two endpoints',
    leader: 'tools-creation.spec.js › MLEADER places a block-backed leader with its text at the anchor',
    tolerance: 'tools-creation.spec.js › TOLERANCE inserts a feature control frame with datum and diameter',
    wipeout: 'tools-creation.spec.js › WIPEOUT closes a masking polygon without deleting what lies beneath',
    region: 'tools-creation.spec.js › REGION turns a selected closed polyline into a region and keeps the source',
    boundary: 'tools-creation.spec.js › BOUNDARY picks inside a closed square and creates its outline',
    centerLine: 'tools-creation.spec.js › CENTERLINE creates an associative midline between two parallel lines',
    centerMark: 'tools-creation.spec.js › CENTERMARK marks a selected circle associatively',
    arcText: 'tools-creation.spec.js › ARCTEXT writes linked text along a selected arc',
    field: 'tools-creation.spec.js › FIELD binds a text to an object length and keeps its definition',
    pointStyle: 'tools-creation.spec.js › DDPTYPE sets the default point style and updates the selected point',
    temporaryTrackingPoint: 'tools-creation.spec.js › TRACKPOINT acquires a tracking origin without adding a vertex',
    offset: 'tools-modification.spec.js › OFFSET copies a line at the given distance on the clicked side',
    trim: 'tools-modification.spec.js › TRIM removes the clicked portion beyond a crossing line',
    extend: 'tools-modification.spec.js › EXTEND moves the clicked endpoint onto the nearest boundary',
    mirror: 'tools-modification.spec.js › MIRROR keeps the source and adds a reflected copy',
    array: 'tools-modification.spec.js › ARRAY and ARRAYCLOSE build a 3 × 2 rectangular array with exact spacing',
    arrayEdit: 'tools-modification.spec.js › ARRAYEDIT changes the saved rows and keeps the array identity',
    arrayPolar: 'tools-modification.spec.js › ARRAYPOLAR places four copies around a typed centre',
    arrayPath: 'tools-modification.spec.js › ARRAYPATH spreads three copies along a picked line',
    break: 'tools-modification.spec.js › BREAK removes the interval between two points of a line',
    breakAtPoint: 'tools-modification.spec.js › BREAKATPOINT splits a line into two touching parts',
    stretch: 'tools-modification.spec.js › STRETCH moves only the vertices inside the crossing window',
    lengthen: 'tools-modification.spec.js › LENGTHEN DELTA adds two metres to the picked end',
    join: 'tools-modification.spec.js › JOIN merges two connected lines into one ordered path',
    xplode: 'tools-modification.spec.js › XPLODE splits a joined path back into lines with part properties',
    align: 'tools-modification.spec.js › ALIGN moves a circle onto destination points without scaling',
    fillet: 'tools-modification.spec.js › FILLET RADIUS 1 rounds a right-angle corner with a tangent arc',
    chamfer: 'tools-modification.spec.js › CHAMFER 1 1 bevels a right-angle corner',
    blend: 'tools-modification.spec.js › BLEND joins two open ends with a tangent cubic spline',
    polylineEdit: 'tools-modification.spec.js › PEDIT INSERT adds a vertex at the requested position',
    splineEdit: 'tools-modification.spec.js › SPLINEDIT CONTROL moves one control point of a spline',
    multilineEdit: 'tools-modification.spec.js › MLEDIT DIAMETERS resizes a donut',
    hatchEdit: 'tools-modification.spec.js › HATCHEDIT changes the pattern spacing and keeps the boundary association',
    hatchToBack: 'tools-modification.spec.js › HATCHTOBACK moves every hatch behind the other objects',
    drawOrder: 'tools-modification.spec.js › DRAWORDER BACK moves the selected object to the start of the order',
    textToFront: 'tools-modification.spec.js › TEXTTOFRONT brings text after every other object',
    transparency: 'tools-modification.spec.js › TRANSPARENCY 50 sets an override on the selection',
    flatten: 'tools-modification.spec.js › FLATTEN PREVIEW reports and FLATTEN ALL clears residual elevations',
    overkill: 'tools-modification.spec.js › OVERKILL ALL removes the exact duplicate and keeps the first identity',
    revisionProperties: 'tools-modification.spec.js › REVCLOUDPROPERTIES rebuilds a revision cloud with a new arc length and direction',
    matchProperties: 'tools-modification.spec.js › MATCHPROP copies layer, colour and line type from a source object',
    layerMatch: 'tools-modification.spec.js › LAYMCH changes only the layer of the target',
    copyToLayer: 'tools-modification.spec.js › COPYTOLAYER duplicates the selection in place on another layer',
    textEdit: 'tools-modification.spec.js › TEXTEDIT opens the in-place editor and replaces the content',
    creationPanel: 'tools-modification.spec.js › CREATIONPANEL edits the radius of a selected circle from the Properties tab',
    resetBlock: 'tools-modification.spec.js › RESETBLOCK restores a dynamic block instance to its defaults',
    arrayClose: 'tools-modification.spec.js › ARRAY and ARRAYCLOSE build a 3 × 2 rectangular array with exact spacing',
    dimension: 'tools-annotation.spec.js › DIMENSION on a picked line creates an associative dimension that follows MOVE',
    linearDimension: 'tools-annotation.spec.js › DIMLINEAR measures an inclined line horizontally',
    alignedDimension: 'tools-annotation.spec.js › DIMALIGNED measures an inclined line along its direction',
    rotatedDimension: 'tools-annotation.spec.js › DIMROTATED 30 measures along a typed angle',
    angularDimension: 'tools-annotation.spec.js › DIMANGULAR dimensions the angle between two picked lines',
    arcDimension: 'tools-annotation.spec.js › DIMARC measures a picked arc length',
    radiusDimension: 'tools-annotation.spec.js › DIMRADIUS dimensions a picked circle and follows a radius edit',
    diameterDimension: 'tools-annotation.spec.js › DIMDIAMETER dimensions a picked circle',
    joggedDimension: 'tools-annotation.spec.js › DIMJOGGED creates a jogged radius on a picked circle',
    ordinateDimension: 'tools-annotation.spec.js › DIMORDINATE records the X ordinate of a picked point',
    quickDimension: 'tools-annotation.spec.js › QDIM creates a continuous series over three collinear lines',
    baselineDimension: 'tools-annotation.spec.js › DIMBASELINE creates a baseline series from the first point',
    continueDimension: 'tools-annotation.spec.js › DIMCONTINUE chains dimensions over two lines',
    dimensionBreak: 'tools-annotation.spec.js › DIMBREAK adds a manual gap on the selected dimension',
    dimensionSpace: 'tools-annotation.spec.js › DIMSPACE spaces parallel dimensions from the base',
    dimensionTextEdit: 'tools-annotation.spec.js › DIMTEDIT POSITION moves the label without changing the measurement',
    dimensionEdit: 'tools-annotation.spec.js › DIMEDIT NEW overrides the label and keeps the measured value token',
    dimensionDisassociate: 'tools-annotation.spec.js › DIMDISASSOCIATE detaches a dimension from its source line',
    dimensionReassociate: 'tools-annotation.spec.js › DIMREASSOCIATE links the selected dimensions to another line',
    dimensionUpdate: 'tools-annotation.spec.js › DIMUPDATE applies the current named style to selected dimensions',
    dimensionRegenerate: 'tools-annotation.spec.js › DIMREGEN refreshes every dimension in one undoable step',
    dimensionInspect: 'tools-annotation.spec.js › DIMINSPECT ON adds an inspection frame and OFF removes it',
    dimensionStyle: 'tools-annotation.spec.js › DIMSTYLE creates, renames and makes a style current',
    centerReassociate: 'tools-annotation.spec.js › CENTERREASSOCIATE moves a centre mark to another circle',
    centerDisassociate: 'tools-annotation.spec.js › CENTERDISASSOCIATE keeps the mark where it is after its circle moves',
    centerReset: 'tools-annotation.spec.js › CENTERRESET restores the default size and extension',
    multiLeaderEdit: 'tools-annotation.spec.js › MLEADEREDIT replaces the leader text',
    multiLeaderAlign: 'tools-annotation.spec.js › MLEADERALIGN X aligns leader contents on the first leader',
    multiLeaderCollect: 'tools-annotation.spec.js › MLEADERCOLLECT merges two leaders into one with both branches',
    multiLeaderStyle: 'tools-annotation.spec.js › MLEADERSTYLE SAVE and USE size the next leader',
    textStyle: 'tools-annotation.spec.js › STYLE opens the text style manager and a new style applies to text',
    multilineStyle: 'tools-annotation.spec.js › MLSTYLE SET defines a two-element style used by MLINE',
    tableStyle: 'tools-annotation.spec.js › TABLESTYLE SET then APPLY changes the selected table',
    tableEdit: 'tools-annotation.spec.js › TABLEDIT CELL sets a value and a formula',
    tableExport: 'tools-annotation.spec.js › TABLEEXPORT downloads the selected table as CSV',
    dataLink: 'tools-annotation.spec.js › DATALINK ATTACH fills a table from a chosen CSV file',
    dataLinkUpdate: 'tools-annotation.spec.js › DATALINKUPDATE reloads a linked table from its CSV source',
    updateField: 'tools-annotation.spec.js › UPDATEFIELD ALL refreshes a field after its source changes',
    objectScale: 'tools-annotation.spec.js › OBJECTSCALE ADD gives annotative text a second scale representation',
    scaleListEdit: 'tools-annotation.spec.js › SCALELISTEDIT ADD and CURRENT update the annotation scale catalogue',
    annotationUpdate: 'tools-annotation.spec.js › ANNOUPDATE and ANNORESET rebase and reset annotative representations',
    annotationReset: 'tools-annotation.spec.js › ANNOUPDATE and ANNORESET rebase and reset annotative representations',
    hyperlink: 'tools-annotation.spec.js › HYPERLINK SET adds a link and REMOVE deletes it',
    geomConstraint: 'tools-constraints.spec.js › GEOMCONSTRAINT creates, lists and deletes a relation',
    gcCoincident: 'tools-constraints.spec.js › GCCOINCIDENT joins the end of one line to the start of another',
    gcCollinear: 'tools-constraints.spec.js › GCCOLLINEAR puts the second line on the first line axis',
    gcConcentric: 'tools-constraints.spec.js › GCCONCENTRIC gives two circles the same centre',
    gcEqual: 'tools-constraints.spec.js › GCEQUAL gives two lines the same length',
    gcFix: 'tools-constraints.spec.js › GCFIX keeps a fixed point while another relation solves',
    gcHorizontal: 'tools-constraints.spec.js › GCHORIZONTAL levels an inclined line',
    gcParallel: 'tools-constraints.spec.js › GCPARALLEL aligns the direction of two lines',
    gcPerpendicular: 'tools-constraints.spec.js › GCPERPENDICULAR sets a right angle between two lines',
    gcSymmetric: 'tools-constraints.spec.js › GCSYMMETRIC mirrors two points about an axis line',
    gcTangent: 'tools-constraints.spec.js › GCTANGENT makes a line touch a circle',
    gcVertical: 'tools-constraints.spec.js › GCVERTICAL makes an inclined line vertical',
    gcSmooth: 'tools-constraints.spec.js › GCSMOOTH joins a spline to a line with continuous tangent',
    autoConstrain: 'tools-constraints.spec.js › AUTOCONSTRAIN PREVIEW reports and AUTOCONSTRAIN squares a near-rectangle',
    dimConstraint: 'tools-constraints.spec.js › DIMCONSTRAINT linear drives a horizontal width',
    dcLinear: 'tools-constraints.spec.js › DCLINEAR w X drives the horizontal extent',
    dcAligned: 'tools-constraints.spec.js › DCALIGNED d drives the true length',
    dcAngular: 'tools-constraints.spec.js › DCANGULAR drives the angle between two lines',
    dcRadius: 'tools-constraints.spec.js › DCRADIUS drives a circle radius',
    dcDiameter: 'tools-constraints.spec.js › DCDIAMETER drives a circle diameter',
    dcConvert: 'tools-constraints.spec.js › DCCONVERT turns an associative dimension into a driving constraint',
    parameters: 'tools-constraints.spec.js › PARAMETERS SET defines a variable that drives a dimensional constraint',
    polar: 'tools-drafting.spec.js › POLAR 45 snaps a pointer-drawn segment onto the 45° increment',
    draftingSettings: 'tools-drafting.spec.js › DSETTINGS opens the drafting settings and a polar change applies',
    drawingUnits: 'tools-drafting.spec.js › UNITS DISPLAY mm formats distances in millimetres',
    ucs: 'tools-drafting.spec.js › UCS SET rotates and moves typed coordinates; UCS WORLD restores them',
    ucsIcon: 'tools-drafting.spec.js › UCSICON OFF hides the UCS indicator and ON shows it again',
    drawingLimits: 'tools-drafting.spec.js › LIMITS refuses points outside the bounds until LIMITS OFF',
    select: 'tools-inquiry.spec.js › SELECT activates the select tool and window selection picks enclosed objects',
    groupEdit: 'tools-inquiry.spec.js › GROUPEDIT ADD, RENAME and REMOVE edit a named group',
    isolateObjects: 'tools-inquiry.spec.js › ISOLATEOBJECTS hides every other object until UNISOLATEOBJECTS',
    selectionFilter: 'tools-inquiry.spec.js › FILTER SAVE and APPLY select the objects matching a stored predicate',
    selectSimilar: 'tools-inquiry.spec.js › SELECTSIMILAR extends the selection to objects of the same type and layer',
    selectCount: 'tools-inquiry.spec.js › SELECTCOUNT reports the selection by type and layer',
    countObjects: 'tools-inquiry.spec.js › COUNT ALL counts every visible object',
    countArea: 'tools-inquiry.spec.js › COUNTAREA counts objects wholly inside a rectangle',
    countList: 'tools-inquiry.spec.js › COUNTLIST GROUP type lists counts without editing the drawing',
    countTable: 'tools-inquiry.spec.js › COUNTTABLE LINKED inserts a query-backed table that refreshes after edits',
    dataExtract: 'tools-inquiry.spec.js › DATAEXTRACTION downloads the extracted objects as CSV',
    measureGeometry: 'tools-inquiry.spec.js › MEASUREGEOM DISTANCE and ANGLE report without editing',
    distanceInquiry: 'tools-inquiry.spec.js › DIST reports distance and deltas between two typed points',
    areaInquiry: 'tools-inquiry.spec.js › AREA reports area and perimeter of a selected rectangle',
    coordinateInquiry: 'tools-inquiry.spec.js › ID reports the coordinates of a typed point',
    entityList: 'tools-inquiry.spec.js › LIST lists the geometry of the selected circle',
    drawingStatus: 'tools-inquiry.spec.js › STATUS reports object, layer and selection counts',
    massProperties: 'tools-inquiry.spec.js › MASSPROP reports area, centroid and moments',
    layerState: 'tools-inquiry.spec.js › LAYERSTATE SAVE and RESTORE bring back layer visibility',
    layerStateSave: 'tools-inquiry.spec.js › LAYERSTATESAVE stores a named state in the catalogue',
    layerIsolate: 'tools-inquiry.spec.js › LAYISO turns off other layers and LAYUNISO restores them',
    layerUnisolate: 'tools-inquiry.spec.js › LAYISO turns off other layers and LAYUNISO restores them',
    layerWalk: 'tools-inquiry.spec.js › LAYWALK shows only the walked layer and END restores the state',
    layerMerge: 'tools-inquiry.spec.js › LAYMRG merges a layer into another and removes it',
    layerTranslate: 'tools-inquiry.spec.js › LAYTRANS maps one layer onto an existing layer',
    layerFilter: 'tools-inquiry.spec.js › LAYERFILTER filters the Layers tab by name',
    layerFlags: 'tools-inquiry.spec.js › LAYER LOCK ON locks a layer so its objects can no longer be moved',
    layerCurrent: 'tools-inquiry.spec.js › LAYMCUR makes the picked object layer current',
    namedView: 'tools-inquiry.spec.js › VIEW SAVE and RESTORE return to a saved zoom',
    viewGo: 'tools-inquiry.spec.js › VIEWGO restores a named view without a history entry',
    zoom: 'tools-inquiry.spec.js › ZOOM 2 halves the view around its centre',
    fit: 'tools-inquiry.spec.js › EXTENTS fits every visible object in the view',
    pan: 'tools-inquiry.spec.js › PAN drags the view with the pointer without a history entry',
    quickCalc: 'tools-inquiry.spec.js › QUICKCALC assigns a session variable and reuses it',
    blockEdit: 'tools-blocks.spec.js › BEDIT opens an isolated draft that leaves the saved model unchanged',
    blockSave: 'tools-blocks.spec.js › BSAVE applies the draft to the definition and every reference',
    blockClose: 'tools-blocks.spec.js › BCLOSE DISCARD abandons the draft and SAVE applies it',
    blockSearch: 'tools-blocks.spec.js › BSEARCH filters the Library tab by block name',
    contentBrowser: 'tools-blocks.spec.js › ADCENTER OPEN lists a library and IMPORT brings one entry in',
    blockExport: 'tools-blocks.spec.js › WBLOCK LIBRARY downloads a library that BLOCKIMPORT brings back',
    blockImport: 'tools-blocks.spec.js › BLOCKIMPORT renames colliding definitions from another drawing',
    blockBase: 'tools-blocks.spec.js › BASE sets the drawing insertion base point',
    blockDetect: 'tools-blocks.spec.js › BLOCKDETECT finds every occurrence of the selected motif without editing',
    blockConvert: 'tools-blocks.spec.js › BCONVERT replaces matching motifs with references to one new block',
    blockReplace: 'tools-blocks.spec.js › BLOCKREPLACE swaps the definition of a reference and keeps its identity',
    blockLookupTable: 'tools-blocks.spec.js › BLOOKUPTABLE builds a variant row and BTABLE applies it',
    blockTable: 'tools-blocks.spec.js › BTABLE APPLY is one undoable step on the selected instance',
    blockVisibility: 'tools-blocks.spec.js › BVSTATE SET defines visibility states switched on an instance',
    blockParameter: 'tools-blocks.spec.js › BPARAMETER defines a parameter in BEDIT and sets it on an instance',
    blockAction: 'tools-blocks.spec.js › BACTION STRETCH bound to a parameter stretches the instance geometry',
    blockCount: 'tools-blocks.spec.js › BCOUNT counts references per block',
    attributeDefine: 'tools-blocks.spec.js › ATTDEF in BEDIT adds an attribute definition to the block',
    attributeEdit: 'tools-blocks.spec.js › ATTEDIT sets one reference value without touching the other',
    attributeSync: 'tools-blocks.spec.js › ATTSYNC gives existing references the new attribute default',
    attributeDisplay: 'tools-blocks.spec.js › ATTDISP OFF hides attribute values and NORMAL restores them',
    attributeManager: 'tools-blocks.spec.js › BATTMAN renames an attribute tag and migrates reference values',
    attributeExtract: 'tools-blocks.spec.js › ATTEXT downloads the attribute values as CSV',
    pasteBlock: 'tools-blocks.spec.js › PASTEBLOCK pastes copied geometry as one anonymous block reference',
    layout: 'tools-layouts.spec.js › LAYOUT FOUR creates a layout with four viewports and opens it',
    pageSetup: 'tools-layouts.spec.js › PAGESETUP opens the page controls and the paper format change applies',
    pageSetupImport: 'tools-layouts.spec.js › PSETOUT downloads page setups that PSETUPIN imports into another drawing',
    pageSetupExport: 'tools-layouts.spec.js › PSETOUT downloads page setups that PSETUPIN imports into another drawing',
    modelSpace: 'tools-layouts.spec.js › MODEL and PSPACE switch between model and the active layout',
    paperSpace: 'tools-layouts.spec.js › MODEL and PSPACE switch between model and the active layout',
    viewportClip: 'tools-layouts.spec.js › VPCLIP gives the selected viewport a clip boundary',
    viewportLayer: 'tools-layouts.spec.js › VPLAYER freezes a layer in one viewport only',
    viewportMax: 'tools-layouts.spec.js › VPMAX maximises the selected viewport and VPMIN returns to the sheet',
    viewportMin: 'tools-layouts.spec.js › VPMAX maximises the selected viewport and VPMIN returns to the sheet',
    alignSpace: 'tools-layouts.spec.js › ALIGNSPACE scales and centres a viewport on paper points',
    changeSpace: 'tools-layouts.spec.js › CHSPACE moves a model object onto the active layout paper',
    exportLayout: 'tools-layouts.spec.js › EXPORTLAYOUT downloads the active layout as a separate drawing',
    plot: 'tools-layouts.spec.js › PLOT writes a one-page PDF of the active layout',
    pdfAll: 'tools-layouts.spec.js › PDFALL writes every layout into one ordered PDF',
    pdfSelected: 'tools-layouts.spec.js › PDFSELECTED writes only the selected layout tab',
    publish: 'tools-layouts.spec.js › PUBLISH previews all layouts and writes a multi-page PDF',
    autoPublish: 'npm run test:headless › native AUTOPUBLISH writes every layout beside the saved drawing',
    dwfx: 'tools-layouts.spec.js › DWFXOUT publishes a DWFx package with one page per layout',
    pngOut: 'tools-layouts.spec.js › PNGOUT WIDTH 256 downloads a PNG within 256 px',
    jpegOut: 'tools-layouts.spec.js › JPGOUT downloads an opaque JPEG',
    svgOut: 'tools-layouts.spec.js › SVGOUT downloads an SVG containing the drawn geometry',
    wmfExport: 'tools-layouts.spec.js › WMFOUT downloads a placeable WMF',
    styleManager: 'tools-layouts.spec.js › STYLESMANAGER opens the plot style manager',
    plotStyle: 'tools-layouts.spec.js › PLOTSTYLE SAVE and APPLY assign a named plot style to the selection',
    convertPlotStyles: 'tools-layouts.spec.js › CONVERTPSTYLES NAMED switches publication to named plot styles',
    convertColorTable: 'tools-layouts.spec.js › CONVERTCTB converts colour rules to named plot assignments',
    newSheetSet: 'tools-layouts.spec.js › NEWSHEETSET creates a sheet set index without touching the drawing',
    openSheetSet: 'tools-layouts.spec.js › OPENSHEETSET reads a sheet set index from the file chooser',
    sheetSet: 'tools-layouts.spec.js › SHEETSET REPORT and SAVE expose and download the sheet index',
    sheetSetArchive: 'npm run test:headless › native ETRANSMIT packages the sheet set index with its source drawing',
    saveTemplate: 'tools-files.spec.js › SAVETEMPLATE downloads the drawing and NEW TEMPLATE instantiates it with a fresh identity',
    quickNew: 'tools-files.spec.js › QNEW without a configured template starts a blank drawing',
    recover: 'tools-files.spec.js › RECOVER reads a damaged archive, REPORT shows the loss and OPEN opens the surviving geometry',
    audit: 'tools-files.spec.js › AUDIT reports an orphan layer reference and AUDIT REPAIR restores it in one undo step',
    purge: 'tools-files.spec.js › PURGE PREVIEW reports unused definitions and PURGE ALL removes them; undo restores',
    drawingCompare: 'tools-files.spec.js › COMPARE reads an edited copy and reports the changed and added objects without editing',
    drawingCompareImport: 'tools-files.spec.js › COMPAREIMPORT ALL applies the compared differences in one undo step',
    drawingStandards: 'tools-files.spec.js › STANDARDS SAVE downloads the definitions and STANDARDS LOAD embeds them',
    drawingCheckStandards: 'tools-files.spec.js › CHECKSTANDARDS lists a nonconforming layer and FIX ALL repairs it in one undo step',
    externalReference: 'tools-files.spec.js › XREF LIST, UNLOAD, RELOAD and DETACH manage the reference state',
    referenceAttach: 'tools-files.spec.js › XATTACH caches the chosen drawing as an external reference at the origin',
    referenceBind: 'tools-files.spec.js › XBIND converts the reference to ordinary block geometry in one undo step',
    referenceClip: 'tools-files.spec.js › XCLIP RECT clips the selected reference; undo removes the clip',
    referenceCompare: 'tools-files.spec.js › XCOMPARE reports the source objects added and removed since attachment',
    imageSource: 'tools-files.spec.js › IMAGE opens the source controls and Embed keeps the snapshot without the link',
    imageClip: 'tools-files.spec.js › IMAGECLIP RECT crops the selected image in local fractions',
    imageAdjust: 'tools-files.spec.js › IMAGEADJUST BRIGHTNESS and MONO store nondestructive adjustments',
    pdfImport: 'tools-files.spec.js › PDFIMPORT turns the PDF line and text into editable objects in one undo step',
    pdfAttach: 'tools-files.spec.js › PDFATTACH places the page as a native underlay at paper scale',
    pdfClip: 'tools-files.spec.js › PDFCLIP RECT clips the selected underlay; undo removes the clip',
    pdfLayers: 'tools-files.spec.js › PDFLAYERS lists the optional-content layers and OFF hides one',
    pdfShxText: 'tools-files.spec.js › PDFSHXTEXT recognises imported SHX strokes as text with the chosen font',
    dgnImport: 'tools-files.spec.js › DGNIMPORT brings levels and geometry in as editable objects in one undo step',
    dgnAttach: 'tools-files.spec.js › DGNATTACH adds one vector reference with its embedded source',
    dgnClip: 'tools-files.spec.js › DGNCLIP RECT clips the selected DGN reference',
    dwfAttach: 'tools-files.spec.js › DWFATTACH attaches a DWFx page as an underlay with a preview',
    dwfClip: 'tools-files.spec.js › DWFCLIP RECT crops the selected DWFx underlay',
    wmfImport: 'tools-files.spec.js › WMFIN imports a WMF written by WMFOUT as editable vector geometry',
    aliasEdit: 'tools-files.spec.js › ALIASEDIT SET defines a personal alias that starts LINE, and REMOVE deletes it',
    copyClip: 'tools-files.spec.js › clipboard › COPYCLIP then PASTECLIP places a copy at the picked point',
    copyBase: 'tools-files.spec.js › clipboard › COPYBASE pastes relative to the picked base point',
    cutClip: 'tools-files.spec.js › clipboard › CUTCLIP removes the selection after copying and PASTEORIG restores it in place',
    pasteOriginal: 'tools-files.spec.js › clipboard › CUTCLIP removes the selection after copying and PASTEORIG restores it in place',
    pasteClip: 'tools-files.spec.js › clipboard › PASTECLIP reads SVG geometry from the plain-text clipboard',
    recoverAll: 'npm run test:headless › native RECOVERALL → RECOVERYMANAGER SELECT/OPEN recovers a damaged root with its reference',
    recoveryManager: 'npm run test:headless › native RECOVERALL → RECOVERYMANAGER SELECT/OPEN recovers a damaged root with its reference',
    referenceEdit: 'npm run test:headless › native REFEDIT → REFSAVE writes the source, REFCLOSE DISCARD keeps it unchanged',
    referenceSave: 'npm run test:headless › native REFEDIT → REFSAVE writes the source, REFCLOSE DISCARD keeps it unchanged',
    referenceClose: 'npm run test:headless › native REFEDIT → REFSAVE writes the source, REFCLOSE DISCARD keeps it unchanged',
    imageAttach: 'npm run test:headless › native IMAGEATTACH links the image file and embeds its snapshot',
};

// Pending successful workflows, grouped by family. Every catalog command is
// currently covered. A new command lands here (with a `TODO(e2e)` note
// describing the scenario) until its workflow test exists.
export const TODO = {};
